sudo: required
language: java
jdk: oraclejdk8

services:
  - docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}

script:
  - ./mvnw clean install -B

after_success:
  - docker login -u $dockerhub-user -p $dockerhub-pass
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCHfi`
  - export IMAGE_NAME=sivaprasadreddy/freelancer-kit
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $heroku-api-key
  app: mcc-currency-app
