sudo: required
language: java
jdk: oraclejdk8

services:
  - docker

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::7}

addons:
  sonarcloud:
    organization: "rodrigovsilva-github"
    token:
      secure: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar


after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCHfi`
  - export IMAGE_NAME=sivaprasadreddy/freelancer-kit
  - docker build -t $IMAGE_NAME:$COMMIT .
  - docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: mcc-currency-app
